# -*- coding: utf-8 -*-
"""Colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZghQWaYkOjIeWuirs0z8yBTMWhvBTnb5

<img style="float: left;" src="https://avatars.githubusercontent.com/u/88348966?s=400&u=9643fc4455139ef6e232241a949da1d6005499e6&v=4" alt="drawing" />

### Welcome to the Repository for the Complete Python Bootcamp!
## Using Colab
Hello guys, welcome back.

In this section, we will show you how to use colab for Python. 

To start using Colab, go to [colab.research.google.com](https://colab.research.google.com)


After Colab loads, create a new notebook by clicking on **File** in the top menu and selecting **new notebook** from the dropdown menu.

A new notebook with code an open code cell will open up.

### Fist line of code on colab.

print("Hello World!")
"""